### ISSUE TITLE
Bug when spy'ing on 2 people

### ISSUE THREAD

**Issue by KawaiiKillar** [sharkbound/RocketModSpyAll#2]
Lets say i spy on "MrJacob" and after i spyed him i spy "MrLol" Then the Spy cam switches between them all the time and it gets confusing

**Comment by sharkbound** [comment]
Its not really a bug. Its because spamspy constantly screenshots those players you spamspy. Do /ss stop to stop your other spamspy before you try to /ss or /spy anyone else

**Comment by sharkbound** [comment]
il add a feature were it will cancel any running /ss's if you try to /ss someone else

**Comment by sharkbound** [comment]
Fixed this.
